version: "3.3"
services:
  api:
    build: .
    ports:
      - 3333:3333
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mysql_storage:/var/lib/mysql

volumes:
  mysql_storage:
